const translations = {
  en: {
    home: "Home",
    description: "This is an example page.",
    i: "I'm",
    abut_h: "About",
    about_p: "Highly skilled Systems Engineer with extensive experience in IT infrastructure management, cybersecurity, automation, and database administration. With a strong technical foundation in Active Directory, SQL Server, O365, and scripting languages like PowerShell, VB Script, and Python, I have successfully led and contributed to large-scale IT projects, including OCBC Bank’s Active Directory and O365 migration. My expertise spans requirement engineering, troubleshooting, stakeholder management, and IT security, making myself a valuable asset in both individual and team environments. I am following an MSc in Information Security from Luleå University of Technology, I hold a MSc in IT (Cyber Security) from the Sri Lanka Institute of Information Technology and BSc in Management Information Systems from UCD Ireland along with industry-recognized certifications like ISC2 CC and CCNA. My professional journey includes roles at NTT Singapore, where I provided global IT support and automation solutions, the Agriculture Sector Modernization Project in Sri Lanka, where I managed IT infrastructure and cybersecurity, and Star Garments, where he ensured seamless IT operations for over 700 users. Fluent in English and Sinhala, with basic Swedish proficiency, I am passionate about problem-solving, automation, and continuous learning, making me a dynamic professional in the field of information security and system administration.",
    sub_h: "System Engineer & Cyber Security Professional",
    person_p: "I am a dedicated and adaptable IT professional born on August 27, 1989, originally from Sri Lanka and currently residing in Sweden. With strong personal values of honesty, reliability, and a continuous drive for professional growth, I bring a disciplined and collaborative approach to every role I undertake. I am married and legally eligible to work internationally, supported by valid identification and travel documentation. Fluent in Sinhala and English, and currently learning Swedish, I am well-prepared to thrive in multicultural and diverse work environments.",
    b_day: "Birthday:",
    web: "Website:",
    phone: "Phone:",
    city: "City:",
    age: "Age:",
    degree: "Degree:",
    email_add: "E-mail:",
    freelance: "Freelance:",
    aboutus: "About",

    skillheading: "Skills",
    skill_p: "I have strong foundation in IT infrastructure, cybersecurity, and automation, possess a diverse skill set that enables me to efficiently manage complex systems, troubleshoot technical challenges, and drive digital transformation. My expertise spans system administration, network security, scripting, database management, and cloud services, complemented by a deep understanding of project management and software development methodologies. I thrive in both independent and collaborative environments, leveraging my analytical and problem-solving abilities to deliver innovative solutions. Below is a detailed breakdown of my technical, project management, and soft skills that contribute to my success in the IT industry",
    tech_skill: "Technical Skills",
    sys_eng_admin: "SYSTEMS ENGINEERING & ADMINISTRATION",
    infra_mgm: "IT INFRASTRUCTURE MANAGEMENT",
    ad_o365: "ACTIVE DIRECTORY & O365 ADMINISTRATION",
    sdlc: "SOFTWARE DEVELOPMENT LIFECYCLE (SDLC) MANAGEMENT",
    svr_install: "SERVER INSTALLATION & MAINTENANCE",
    it_proc: "IT PROCUREMENT & VENDOR MANAGEMENT",
    db_admin: "DATABASE ADMINISTRATION (SQL SERVER)",
    sys_sec: "SYSTEM SECURITY & MONITORING",
    script: "AUTOMATION & SCRIPTING (POWERSHELL, VB SCRIPT, PYTHON)",
    network: "NETWORK ADMINISTRATION & TROUBLESHOOTING",
    cloud: "CLOUD SERVICES (O365, AZURE)",
    pm: "Project Management & Analysis",
    req_eng: "REQUIREMENT ENGINEERING (BRD, FRD, UML DIAGRAMS)",
    project_mgm: "IT PROJECT MANAGEMENT & DOCUMENTATION",
    dev_method: "SOFTWARE DEVELOPMENT METHODOLOGIES",
    agile: "AGILE & SCRUM PRACTICES",
    prob_solv: "PROBLEM-SOLVING & DECISION-MAKING",
    soft_skill: "Soft Skills",
    comm_stak_mgm: "STRONG COMMUNICATION & STAKEHOLDER MANAGEMENT",
    team_lead: "TEAM COLLABORATION & LEADERSHIP",
    tran_doc: "TRAINING & TECHNICAL DOCUMENTATION",
    adapt: "ADAPTABILITY & CONTINUOUS LEARNING",
    attn_acc: "ATTENTION TO DETAIL & ACCURACY",
    tools_tech: "Tools & Technologies",
    jira_conf: "JIRA & CONFLUENCE",
    sql_mgm: "SQL SERVER MANAGEMENT STUDIO",
    vs: "VISUAL STUDIO",
    deawio_photoshop: "DRAW.IO & ADOBE PHOTOSHOP",
    remote_spt: "REMOTE SUPPORT TOOLS (TEAMVIEWER, VNC SERVER)",
    github: "GITHUB",
    language_prof: "Language Proficiency",
    sin: "SINHALA",
    swed: "SWEDISH",
    eng: "ENGLISH",

    profexph: "Professional Experience",
    prof_exp_p: "Experienced Systems Engineer with expertise in IT infrastructure management, cybersecurity, automation, and database administration. I have strong background in stakeholder management, troubleshooting, system security, and scripting, with a commitment to continuous learning and professional development.",
    work_exp: "Work Experience",
    sys_eng: "SYSTEM ENGINEER",
    ntt1: "Led the post-migration support team for OCBC Bank’s Active Directory and Office 365 migration project, ensuring secure and seamless transitions across multiple global offices while maintaining data integrity and endpoint security.",
    ntt2: "Developed and executed PowerShell and VB Script automation to streamline system migration tasks, including workstation performance validation, log processing, and pre-migration system checks, enhancing overall system administration efficiency.",
    ntt3: "Conducted in-depth assessments for credential validation, network security, antivirus status, and security policy compliance, adhering to cybersecurity standards and mitigating potential vulnerabilities.",
    ntt4: "Provided comprehensive remote and on-site support to international offices (Singapore, Malaysia, Dubai, Philippines, UK, Luxembourg), resolving Office 365 and Active Directory integration issues and ensuring secure, uninterrupted access.",
    ntt5: "Managed issue logs and incidents, collaborating with third-party vendors and application custodians to ensure timely resolution and compliance with cybersecurity protocols and service-level agreements.",
    ntt6: "Authored detailed technical documentation, including user guides and troubleshooting manuals, to support knowledge sharing and best practices across the team.",
    ntt7: "Assisted with Microsoft Intune and O365 troubleshooting during post-migration clinics, reinforcing endpoint security and ensuring smooth system integration for users.",
    ntt8: "Maintained a proactive approach to system security, user access management, and infrastructure resilience throughout all phases of the project, aligning with enterprise cybersecurity frameworks.",
    ict_officer: "ICT OFFICER",
    asmp: "Agriculture Sector Modernization Project, Sri Lanka",
    ministry: "(World Bank funded project under Ministry of Primary Industries, Sri Lanka)",
    asmp1: "Managed and maintained the organization’s IT infrastructure, including servers, firewalls, and organizational networks, with a strong focus on system security and network resilience.",
    asmp2: "Delivered L1 and L2 support to project staff and beneficiaries, diagnosing and resolving software, hardware, and cybersecurity issues to ensure operational continuity.",
    asmp3: "Developed and executed PowerShell and VB Script automation to streamline system migration tasks, including workstation performance validation, log processing, and pre-migration system checks, enhancing overall system administration efficiency.",
    asmp4: "Administered and secured organizational databases, overseeing data integrity, regular backups, and access control to safeguard sensitive project information.",
    asmp5: "Led and participated in system feasibility studies, designing and implementing moderately complex IT systems, including automation and software enhancements.",
    asmp6: "Collaborated with external vendors and service providers for the procurement and maintenance of secure and compliant IT services, ensuring adherence to security standards and service-level agreements.",
    asmp7: "Prepared and maintained detailed technical documentation, including BRDs, FRDs, UML diagrams, and system logs to support requirement engineering and process transparency.",
    asmp8: "Oversaw the migration of desktop applications (e.g., O365) and operating systems, ensuring minimal downtime and complete alignment with cybersecurity protocols.",
    asmp9: "Conducted cybersecurity awareness training for project staff and beneficiaries, educating them on topics such as phishing prevention, secure data handling, password security, and safe use of email and internet resources.",
    asmp10: "Created training materials and user manuals to support ongoing IT security education and foster a cyber-aware organizational culture.",
    asmp11: "Actively participated in Agile ceremonies, contributing to sprint planning, prioritizing requirements, and ensuring timely delivery of secure and functional system updates.",
    it_exec: "IT EXECUTIVE",
    star1: "Configured, maintained, and troubleshot the company’s IT infrastructure, including workstations, networks, and servers, ensuring system reliability and data security.",
    star2: "Provided L1 and L2 support to over 700 users across the main factory and six branch locations, resolving issues related to hardware, software, and network security.",
    star3: "Administered and secured O365 and Zimbra mail systems, including user account setup, authentication levels, and routine troubleshooting aligned with cybersecurity best practices.",
    star4: "Managed Active Directory operations such as user provisioning, permission settings, and access control, helping mitigate unauthorized access risks.",
    star5: "Delivered cybersecurity awareness training to new and existing employees, covering topics such as phishing prevention, password hygiene, and identifying suspicious emails to enhance the organization’s security posture.",
    star6: "Conducted periodic workshops and one-on-one sessions to reinforce safe IT practices and promote a cyber-aware culture across departments.",
    star7: "Maintained detailed documentation of IT infrastructure, incidents, and vendor service-level agreements to ensure consistency, compliance, and risk mitigation.",
    star8: "Provided support across Microsoft Windows and Office application suites, with a focus on patch management, software updates, and minimizing security vulnerabilities.",
    star9: "Utilized TeamViewer and VNC Server for secure remote troubleshooting and system updates, ensuring continued productivity and endpoint protection across all sites.",

    eduqulih: "Education Qualification",
    edu_quli_p: "I have a strong academic background in Information Security and Information Technology, specializing in cybersecurity, system administration, and network security. I am currently pursuing an MSc in Information Security at Luleå University of Technology, Sweden, and an MSc in IT (Cyber Security) at Sri Lanka Institute of Information Technology, further enhancing my expertise in securing digital environments. I hold a BSc in Management Information Systems from University College Dublin, Ireland, which provided me with a solid foundation in IT infrastructure, database management, and software development. Additionally, I have earned industry-recognized certifications, including the ISC2 CC (2024) and CCNA (2020), demonstrating my proficiency in network security, risk management, and IT governance. My continuous pursuit of education and certifications reflects my commitment to staying updated with evolving technology trends and security best practices.",
    edu: "Education",
    mscis: "MSC IN INFORMATION SECURITY",
    present: "2024 - Present",
    lulea_uni: "Luleå Technical University, Skellefteå",
    lulea_uni_des: "Following Masters degree in Information Security.",
    msccs: "MSC IN INFORMATION TECHNOLOGY (CYBER SECURITY)",
    sliit_des: "Completed MSc in Information Technology Specialized in Cyber Security (Effective from March 2024)",
    bscmis: "BSC IN MANAGEMENT INFORMATION SYSTEMS",
    ucd_des: "Completed BSc in Management Information Systems with the Second Class Honors. (Effective from the July 2015)",
    prof_quali: "Professional Qualifications",
    cert_cs: "CERTIFIED IN CYBERSECURITY",
    cert_cs_des: "Completed Certification of Cybersecurity ICS2 CC professional exam.",
    ccna1: "Completed Introduction to Networking.",
    ccna2: "Completed Switching, Routing & Wireless Essentials.",
    ccna3: "Completed Enterprise networking Security & Automation.",

    photographyh: "Photography as a Hobby",
    photography_des: "Outside of my professional life, I am passionate about photography and traveling. Photography allows me to express creativity and attention to detail, while traveling exposes me to new cultures, perspectives, and environments—broadening my understanding of the world. These activities not only refresh and inspire me but also enhance my problem-solving and observational skills, which I bring into my professional work.",
    all: "All",
    portrait: "Portraits",
    events: "Events",
    wild_life: "Wild Life",
    other_poto: "Other",

    testimonialh: "Testimonials",
    ass_cons: "Associate Consultant, Digital Workplace",
    hr_mgr: "Group Manager - HR",
    com: "Chalaka is a very delegated person whom I had worked with who always goes the extra mile to complete his task and help others in need in a very harsh and challenging project. I'm so glad I worked with him and have become friends with him along the way. He's a very knowledgeable person to have on any Team. Great Team player and support. I would recommend him to anyone who is looking to hire him.",
    com2: "I had the privilege of working closely with Chalaka during the OCBC post AD migration project, and it's safe to say that his contributions were invaluable to our team's success. This project was nothing short of challenging, but Chalaka's dedication and exceptional teamwork made all the difference. Chalaka consistently demonstrated a high level of responsibility and approached each challenge with a positive attitude and a solutions-oriented mindset. I never once heard him complain, which his determination and commitment to seeing the project through were remarkable. A great team player with the ability to work seamlessly with others, we discussed and learned from one another and I am grateful for the opportunity to have worked with him. Keep it going brother!",
    com3: "I had the pleasure of working with Chalaka for 3 1/2 years at the Agriculture Sector Modernization Project, collaborating on several projects as a team. I started my work journey with him in 2018, and he helped me understand the company’s internal process. His work ethic is pristine, and he is easily adjustable to a given situation. His ability to go out of his way to help others has made him stand out and I've witnessed several times that he handled all critical situations in an appreciative & positive manner with warm smiles. His multitasking ability was unlike I've seen before and made an applause-worthy increase in our project growth level. As an IT professional consistently gave 100 percent effort to the team and played a significant role in ensuring that he completed assignments on time. He has excellent and wise potential in the field of IT and Project Management. Any team would be lucky to have Chalaka as an IT professional. Best wishes to his future endeavours.",

    contacth: "Contact",
    location: "Location:",
    email: "E-mail:",
    location_now: "Skellefteå, Sweden",
    call: "Call:",
    address: "Labororatogränd 1C, 1121, Skellefteå, Sweden. 93162",

    copy_r: "Copyright 2025 ChalakaJayaweera. All Rights Reserved",
    design: "Designed by Chalaka Jayaweera",
    
  },
  se: {
    home: "Hem",
    description: "Det här är en exempel-sida.",
    i: "Jag är",
    abut_h: "Om mig",
    about_p: "Mycket skicklig systemingenjör med omfattande erfarenhet av IT-infrastrukturhantering, cybersäkerhet, automation och databasadministration. Med en stark teknisk grund i Active Directory, SQL Server, O365 och skriptspråk som PowerShell, VB Script och Python har jag framgångsrikt lett och bidragit till storskaliga IT-projekt, inklusive OCBC Banks Active Directory och O365-migrering. Min expertis omfattar kravhantering, felsökning, intressenthantering och IT-säkerhet, vilket gör mig till en värdefull tillgång i både individuella och teammiljöer. Jag har en masterexamen i informationssäkerhet från Luleå tekniska universitet, en masterexamen i IT (cybersäkerhet) från Sri Lanka Institute of Information Technology och en kandidatexamen i Management Information Systems från UCD Ireland, tillsammans med branschgodkända certifieringar som ISC2 CC och CCNA. Min professionella resa inkluderar roller på NTT Singapore, där jag tillhandahöll global IT-support och automationslösningar, jordbrukssektorns moderniseringsprojekt i Sri Lanka, där jag hanterade IT-infrastruktur och cybersäkerhet, och Star Garments, där han säkerställde en smidig IT-drift för över 700 användare. Jag talar flytande engelska och singalesiska, med grundläggande kunskaper i svenska, och brinner för problemlösning, automatisering och kontinuerligt lärande, vilket gör mig till en dynamisk yrkesperson inom informationssäkerhet och systemadministration.",
    sub_h: "Systemingenjör och cybersäkerhetsexpert",
    person_p: "Jag är en engagerad och anpassningsbar IT-expert, född 27 augusti 1989, ursprungligen från Sri Lanka och för närvarande bosatt i Sverige. Med starka personliga värderingar som ärlighet, pålitlighet och en ständig strävan efter professionell utveckling, tillför jag en disciplinerad och samarbetsinriktad inställning till varje roll jag åtar mig. Jag är gift och har laglig rätt att arbeta internationellt, med stöd av giltig legitimation och resehandlingar. Jag talar flytande singalesiska och engelska, och lär mig för närvarande svenska, vilket gör mig väl förberedd att trivas i mångkulturella och mångsidiga arbetsmiljöer.",
    b_day: "Födelsedag:",
    web: "Hemsida:",
    phone: "Telefon:",
    city: "Stad:",
    age: "Ålder:",
    degree: "Examen:",
    email_add: "E-post:",
    freelance: "Frilans:",
     aboutus: "Om mig",

    skillheading: "Färdigheter",
    skill_p: "Jag har en stark grund inom IT-infrastruktur, cybersäkerhet och automation, och besitter en bred kompetens som gör det möjligt för mig att effektivt hantera komplexa system, lösa tekniska problem och driva digital transformation. Min expertis omfattar systemadministration, nätverkssäkerhet, skriptning, databashantering och molntjänster, kompletterad av en djup förståelse för projektledning och mjukvaruutvecklingsmetodik. Jag trivs både självständigt och i team, och använder min analytiska förmåga och problemlösningsförmåga för att leverera innovativa lösningar. Nedan följer en detaljerad översikt av mina tekniska färdigheter, projektledningsförmågor och mjuka färdigheter som bidrar till min framgång inom IT-branschen.",
    tech_skill: "Tekniska Färdigheter",
    sys_eng_admin: "SYSTEMINGENJÖRING & ADMINISTRATION",
    infra_mgm: "HANTERING AV IT-INFRASTRUKTUR",
    ad_o365: "ACTIVE DIRECTORY & O365-ADMINISTRATION",
    sdlc: "HANTERING AV MJUKVARANS LIVSCYKEL (SDLC)",
    svr_install: "SERVERINSTALLATION & UNDERHÅLL",
    it_proc: "IT-INKÖP & LEVERANTÖRSHANTERING",
    db_admin: "DATABASADMINISTRATION (SQL SERVER)",
    sys_sec: "SYSTEMSÄKERHET & ÖVERVAKNING",
    script: "AUTOMATION & SKRIPTNING (POWERSHELL, VB SCRIPT, PYTHON)",
    network: "NÄTVERKSADMINISTRATION & FELSÖKNING",
    cloud: "MOLNTJÄNSTER (O365, AZURE)",
    pm: "Projektledning & Analys",
    req_eng: "KRAVINSAMLING (BRD, FRD, UML-DIAGRAM)",
    project_mgm: "IT-PROJEKTLEDNING & DOKUMENTATION",
    dev_method: "MJUKVARUUTVECKLINGSMETODER",
    agile: "AGILA & SCRUM-METODER",
    prob_solv: "PROBLEMLÖSNING & BESLUTSFATTANDE",
    soft_skill: "Mjuka Färdigheter",
    comm_stak_mgm: "STARK KOMMUNIKATION & INTRESSENTHANTERING",
    team_lead: "TEAMARBETE & LEDARSKAP",
    tran_doc: "UTBILDNING & TEKNISK DOKUMENTATION",
    adapt: "ANPASSNINGSFÖRMÅGA & KONTINUERLIGT LÄRANDE",
    attn_acc: "NOGGRANNHET & PRECISION",
    tools_tech: "Verktyg & Tekniker",
    jira_conf: "JIRA & CONFLUENCE",
    sql_mgm: "SQL SERVER MANAGEMENT STUDIO",
    vs: "VISUAL STUDIO",
    deawio_photoshop: "DRAW.IO & ADOBE PHOTOSHOP",
    remote_spt: "FJÄRRSTÖDSVERKTYG (TEAMVIEWER, VNC SERVER)",
    github: "GITHUB",
    language_prof: "Språkkunskaper",
    sin: "SINGALESISKA",
    swed: "SVENSKA",
    eng: "ENGELSKA",

    profexph: "Yrkeserfarenhet",
    prof_exp_p: "Erfaren systemingenjör med expertis inom IT-infrastrukturhantering, cybersäkerhet, automation och databashantering. Jag har en stark bakgrund inom intressenthantering, felsökning, systemsäkerhet och skriptning, med ett engagemang för kontinuerligt lärande och professionell utveckling.",
    work_exp: "Arbetserfarenhet",
    sys_eng: "SYSTEMINGENJÖR",
    ntt1: "Ledde eftermigreringssupportteamet för OCBC Banks migreringsprojekt av Active Directory och Office 365, vilket säkerställde säkra och smidiga övergångar på flera globala kontor samtidigt som dataintegritet och endpunktsäkerhet bibehölls.",
    ntt2: "Utvecklade och genomförde PowerShell- och VB-skript för att automatisera systemmigreringsuppgifter, inklusive validering av arbetsstationsprestanda, loggbearbetning och förkontroller av system, vilket förbättrade effektiviteten i systemadministrationen.",
    ntt3: "Genomförde djupgående bedömningar för autentiseringsvalidering, nätverkssäkerhet, antivirusstatus och efterlevnad av säkerhetspolicys, i enlighet med cybersäkerhetsstandarder och riskminimering.",
    ntt4: "Tillhandahöll omfattande fjärr- och platsstöd till internationella kontor (Singapore, Malaysia, Dubai, Filippinerna, Storbritannien, Luxemburg) och löste integrationsproblem med Office 365 och Active Directory för att säkerställa säker och oavbruten åtkomst.",
    ntt5: "Hanterade ärendeloggar och incidenter samt samarbetade med tredjepartsleverantörer och applikationsansvariga för att säkerställa snabb lösning och efterlevnad av cybersäkerhetsprotokoll och servicenivåavtal.",
    ntt6: "Författade detaljerad teknisk dokumentation, inklusive användarhandböcker och felsökningsmanualer, för att stödja kunskapsdelning och bästa praxis inom teamet.",
    ntt7: "Assisterade med felsökning av Microsoft Intune och O365 under eftermigreringskliniker, vilket stärkte endpunktsäkerheten och säkerställde smidig systemintegration för användarna.",
    ntt8: "Bibehöll ett proaktivt tillvägagångssätt för systemsäkerhet, hantering av användaråtkomst och infrastrukturens motståndskraft under hela projektet, i linje med företagets cybersäkerhetsramverk.",
    ict_officer: "IT-ANSVARIG",
    asmp: "Projektet för modernisering av jordbrukssektorn, Sri Lanka",
    ministry: "(Världsbankfinansierat projekt under Ministeriet för primärnäringar, Sri Lanka)",
    asmp1: "Hanterade och underhöll organisationens IT-infrastruktur, inklusive servrar, brandväggar och nätverk, med starkt fokus på systemsäkerhet och nätverkets motståndskraft.",
    asmp2: "Tillhandahöll L1- och L2-support till projektpersonal och förmånstagare, diagnostiserade och löste programvaru-, hårdvaru- och cybersäkerhetsproblem för att säkerställa kontinuerlig drift.",
    asmp3: "Utvecklade och genomförde PowerShell- och VB-skript för att automatisera systemmigreringsuppgifter, inklusive validering av arbetsstationsprestanda, loggbearbetning och förkontroller av system, vilket förbättrade systemadministrationens effektivitet.",
    asmp4: "Administrerade och skyddade organisationens databaser, övervakade dataintegritet, regelbundna säkerhetskopieringar och åtkomstkontroller för att skydda känslig projektinformation.",
    asmp5: "Ledde och deltog i genomförbarhetsstudier av system, samt utformade och implementerade måttligt komplexa IT-system, inklusive automation och programvaruförbättringar.",
    asmp6: "Samarbetade med externa leverantörer och tjänsteleverantörer för inköp och underhåll av säkra och regeluppfyllande IT-tjänster, och säkerställde efterlevnad av säkerhetsstandarder och servicenivåavtal.",
    asmp7: "Förberedde och underhöll detaljerad teknisk dokumentation, inklusive BRD:er, FRD:er, UML-diagram och systemloggar för att stödja kravhantering och öppenhet i processer.",
    asmp8: "Övervakade migrering av skrivbordsapplikationer (t.ex. O365) och operativsystem, vilket säkerställde minimal driftstopp och fullständig efterlevnad av cybersäkerhetsprotokoll.",
    asmp9: "Genomförde cybersäkerhetsutbildning för projektpersonal och förmånstagare, med fokus på ämnen som nätfiske, säker datahantering, lösenordssäkerhet och säker användning av e-post och internetresurser.",
    asmp10: "Skapade utbildningsmaterial och användarhandböcker för att stödja löpande IT-säkerhetsutbildning och främja en cybersäker organisationskultur.",
    asmp11: "Deltog aktivt i agila ceremonier, bidrog till sprintplanering, prioriterade krav och säkerställde snabb leverans av säkra och fungerande systemuppdateringar.",
    it_exec: "IT-SPECIALIST",
    star1: "Konfigurerade, underhöll och felsökte företagets IT-infrastruktur, inklusive arbetsstationer, nätverk och servrar, och säkerställde systemsäkerhet och tillförlitlighet.",
    star2: "Tillhandahöll L1- och L2-support till över 700 användare på huvudfabriken och sex filialer, löste problem relaterade till hårdvara, mjukvara och nätverkssäkerhet.",
    star3: "Administrerade och säkrade O365- och Zimbra-e-postsystem, inklusive skapande av användarkonton, autentiseringsnivåer och rutinmässig felsökning i enlighet med cybersäkerhetsrutiner.",
    star4: "Hanterade Active Directory-operationer såsom användarskapande, behörighetsinställningar och åtkomstkontroller, vilket minskade risken för obehörig åtkomst.",
    star5: "Tillhandahöll cybersäkerhetsutbildning till nya och befintliga anställda, med fokus på nätfiskeförebyggande, lösenordssäkerhet och identifiering av misstänkta e-postmeddelanden för att förbättra organisationens säkerhetskultur.",
    star6: "Genomförde återkommande workshops och individuella sessioner för att förstärka säkra IT-praktiker och främja en cybersäkerhetsmedveten kultur i hela organisationen.",
    star7: "Underhöll detaljerad dokumentation av IT-infrastruktur, incidenter och servicenivåavtal med leverantörer för att säkerställa konsekvens, efterlevnad och riskminimering.",
    star8: "Tillhandahöll support för Microsoft Windows och Office-applikationer med fokus på patchhantering, programuppdateringar och att minimera säkerhetsrisker.",
    star9: "Använde TeamViewer och VNC Server för säker fjärrfelsökning och systemuppdateringar, vilket säkerställde produktivitet och skydd av endpunkter på samtliga platser.",
    
    eduqulih: "Utbildningskvalifikationer",
    edu_quli_p: "Jag har en stark akademisk bakgrund inom informationssäkerhet och informationsteknik, med specialisering inom cybersäkerhet, systemadministration och nätverkssäkerhet. Jag studerar för närvarande en masterexamen i informationssäkerhet vid Luleå tekniska universitet i Sverige och en masterexamen i IT (cybersäkerhet) vid Sri Lanka Institute of Information Technology, vilket ytterligare stärker min expertis inom säkring av digitala miljöer. Jag har en kandidatexamen i Management Information Systems från University College Dublin, Irland, vilket gav mig en solid grund inom IT-infrastruktur, databashantering och mjukvaruutveckling. Dessutom har jag erhållit branschcertifieringar, inklusive ISC2 CC (2024) och CCNA (2020), vilket visar min kompetens inom nätverkssäkerhet, riskhantering och IT-styrning. Min kontinuerliga strävan efter utbildning och certifieringar speglar mitt engagemang för att hålla mig uppdaterad med tekniktrender och bästa säkerhetspraxis.",
    edu: "Utbildning",
    mscis: "MASTER I INFORMATIONSSÄKERHET",
    present: "2024 - Pågående",
    lulea_uni: "Luleå tekniska universitet, Skellefteå",
    lulea_uni_des: "Studerar masterprogrammet i informationssäkerhet.",
    msccs: "MASTER I INFORMATIONSTEKNIK (CYBERSÄKERHET)",
    sliit_des: "Avslutade masterexamen i informationsteknik med inriktning mot cybersäkerhet (gäller från mars 2024)",
    bscmis: "KANDIDATEXAMEN I MANAGEMENT INFORMATION SYSTEMS",
    ucd_des: "Avslutade kandidatexamen i Management Information Systems med andra klassens hedersbetyg (gäller från juli 2015)",
    prof_quali: "Professionella kvalifikationer",
    cert_cs: "CERTIFIERAD INOM CYBERSÄKERHET",
    cert_cs_des: "Avklarad cybersäkerhetscertifiering ICS2 CC yrkesexamen.",
    ccna1: "Avslutat Introduktion till nätverk.",
    ccna2: "Avslutat Växling, Ruttning och Trådlösa grunder.",
    ccna3: "Avslutat Företagsnätverk, Säkerhet och Automation.",

    photographyh: "Fotografi som hobby",
    photography_des: "Utanför mitt yrkesliv är jag passionerad för fotografi och resor. Fotografi låter mig uttrycka kreativitet och uppmärksamhet på detaljer, medan resor utsätter mig för nya kulturer, perspektiv och miljöer—vilket breddar min förståelse av världen. Dessa aktiviteter ger mig inte bara ny energi och inspiration utan förbättrar också mina problemlösnings- och observationsförmågor, som jag tar med mig in i mitt yrkesliv.",
    all: "Alla",
    portrait: "Porträtt",
    events: "Evenemang",
    wild_life: "Vilda djur",
    other_poto: "Annat",

    testimonialh: "Rekommendationer",
    ass_cons: "Associate Consultant, Digital Workplace",
    hr_mgr: "Gruppchef - HR",
    com: "Chalaka är en mycket engagerad person som jag har arbetat med och som alltid gör det lilla extra för att slutföra sina uppgifter och hjälpa andra i behov, även i mycket tuffa och utmanande projekt. Jag är glad att jag arbetade med honom och att vi blev vänner under tiden. Han är en mycket kunnig person att ha i vilket team som helst. En fantastisk lagspelare och ett bra stöd. Jag rekommenderar honom varmt till alla som överväger att anställa honom.",
    com2: "Jag hade privilegiet att arbeta nära Chalaka under OCBC:s AD-migrationsprojekt, och det är säkert att säga att hans insatser var ovärderliga för vårt teams framgång. Projektet var minst sagt utmanande, men Chalakas engagemang och enastående samarbetsförmåga gjorde all skillnad. Chalaka visade ständigt ett högt ansvarstagande och bemötte varje utmaning med en positiv attityd och ett lösningsfokuserat sinne. Jag hörde honom aldrig klaga, vilket visade hans beslutsamhet och vilja att driva projektet i mål. En fantastisk lagspelare med förmåga att arbeta sömlöst med andra, vi diskuterade och lärde oss av varandra och jag är tacksam för möjligheten att ha arbetat med honom. Fortsätt så, broder!",
    com3: "Jag hade nöjet att arbeta med Chalaka i 3 1/2 år på Agriculture Sector Modernization Project, där vi samarbetade i flera projekt som ett team. Jag började min arbetsresa med honom 2018, och han hjälpte mig att förstå företagets interna processer. Hans arbetsmoral är oklanderlig, och han anpassar sig lätt till olika situationer. Hans vilja att hjälpa andra gör honom utmärkande, och jag har sett honom hantera kritiska situationer på ett uppskattande och positivt sätt med ett varmt leende. Hans förmåga att multitaska var som jag aldrig tidigare sett och gjorde en applådvärd insats för projektets tillväxt. Som IT-professionell gav han alltid 100 procent till teamet och spelade en viktig roll för att slutföra uppgifter i tid. Han har utmärkta och kloka färdigheter inom IT och projektledning. Vilket team som helst skulle ha turen att ha Chalaka som IT-professionell. Lycka till i framtiden.",

    contacth: "Kontakt",
    location: "Plats:",
    location_now: "Skellefteå, Sverige",
    email: "E-post:",
    call: "Ring:",
    address: "Laboratoriegränd 1C, 1121, Skellefteå, Sverige. 93162",

    copy_r: "Copyright 2025 ChalakaJayaweera. Alla rättigheter förbehållna",
    design: "Designad av Chalaka Jayaweera",

  }
};

function setLanguage(lang) {
  const elements = Object.keys(translations[lang] || {});
  elements.forEach(id => {
    const el = document.getElementById(id);
    if (el) el.textContent = translations[lang][id];
  });
}

// Get language from URL (e.g., ?lang=sv)
function getLanguageFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return params.get("lang") || "en"; // fallback to English
}

// Set language on page load
window.onload = () => {
  const lang = getLanguageFromUrl();
  setLanguage(lang);
};
